<?php


/**
 * Skeleton subclass for representing a row from the 'gender' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Oct  8 23:31:33 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Gender extends BaseGender {

        public function __toString() {
                return $this->getName();
        }

} // Gender
