<?php


/**
 * Skeleton subclass for performing query and update operations on the 'scheduled' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 12 19:48:43 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ScheduledPeer extends BaseScheduledPeer {

} // ScheduledPeer
